services:
  # FastAPI Application  
  api:
    build:
      context: ..
      dockerfile: devel/Dockerfile
    container_name: spec_inspector_api
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - ../.env  # Read ALL variables from .env
    environment:
      # Only override what's different in Docker
      - API_HOST=0.0.0.0
      - PYTHONPATH=/app
    volumes:
      - ../data:/app/data
      - ../logs:/app/logs
      # Mount source code for development (enables live reload)
      - ../backend/api:/app/api
      - ../backend/config:/app/config
      - ../backend/utils:/app/utils
    networks:
      - spec_inspector
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    command: ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

networks:
  spec_inspector:
    driver: bridge